version: '3.4'

services:
  vmailclient:
    image: vmailclient
    container_name: vmail-client
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000